# Generated by Django 2.2 on 2021-06-08 00:40

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Solo_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Post',
        ),
    ]
