# Generated by Django 2.2 on 2021-06-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_App', '0004_auto_20210607_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('file', models.FileField(upload_to='user_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Solo_App.User')),
            ],
        ),
    ]
